# MEGA SCRIPT - Criar TODAS as 30 páginas restantes de uma vez
$basePath = "c:\Users\X472795\Desktop\Projetos\tem-de-tudo\backend\public"
$pages = @(
    @{name="contato.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Contato - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family:Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:40px 20px;text-align:center;"><div style="width:70px;height:70px;background:rgba(255,255,255,0.2);border-radius:50%;display:inline-flex;align-items:center;justify-content:center;margin-bottom:16px;"><i class="fas fa-sparkles" style="font-size:35px;"></i></div><h1 style="font-size:32px;font-weight:900;margin:0;">Fale Conosco</h1></header><div style="max-width:700px;margin:0 auto;padding:32px 20px;"><div style="background:white;border-radius:24px;padding:32px;box-shadow:0 12px 40px rgba(102,126,234,0.08);"><p style="color:#7c8db0;text-align:center;margin:0;">Email: contato@temdetudo.com.br<br>WhatsApp: (11) 99999-9999</p></div></div></body></html>'},
    @{name="planos.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Planos - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:40px 20px;text-align:center;"><h1 style="font-size:32px;font-weight:900;margin:0;">Nossos Planos</h1></header><div style="max-width:1200px;margin:0 auto;padding:32px 20px;"><div style="background:white;border-radius:24px;padding:40px;text-align:center;box-shadow:0 12px 40px rgba(102,126,234,0.08);"><h2 style="font-size:28px;font-weight:900;color:#667eea;margin:0 0 16px;">Plano Premium</h2><div style="font-size:48px;font-weight:900;color:#1a1a2e;margin-bottom:8px;">R$ 99</div><p style="color:#7c8db0;">por mês</p></div></div></body></html>'},
    @{name="termos.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Termos de Uso - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;900&display=swap" rel="stylesheet"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;padding:40px 20px;"><div style="max-width:900px;margin:0 auto;background:white;border-radius:24px;padding:40px;box-shadow:0 12px 40px rgba(102,126,234,0.08);"><h1 style="font-size:32px;font-weight:900;color:#1a1a2e;margin:0 0 24px;">Termos de Uso</h1><p style="color:#7c8db0;line-height:1.8;">Ao utilizar nossa plataforma, você concorda com nossos termos e condições de uso...</p></div></body></html>'},
    @{name="privacidade.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Política de Privacidade - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;900&display=swap" rel="stylesheet"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;padding:40px 20px;"><div style="max-width:900px;margin:0 auto;background:white;border-radius:24px;padding:40px;box-shadow:0 12px 40px rgba(102,126,234,0.08);"><h1 style="font-size:32px;font-weight:900;color:#1a1a2e;margin:0 0 24px;">Política de Privacidade</h1><p style="color:#7c8db0;line-height:1.8;">Respeitamos sua privacidade e protegemos seus dados...</p></div></body></html>'},
    @{name="meu-qrcode.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Meu QR Code - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><script src="https://cdn.jsdelivr.net/npm/qrcode@1.5.1/build/qrcode.min.js"></script></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:40px 20px;text-align:center;"><h1 style="font-size:28px;font-weight:900;margin:0;">Meu QR Code</h1></header><div style="max-width:600px;margin:0 auto;padding:32px 20px;text-align:center;"><div style="background:white;border-radius:24px;padding:40px;box-shadow:0 20px 60px rgba(102,126,234,0.12);"><canvas id="qr" style="max-width:100%;"></canvas></div></div><script>const userData={type:"cliente_checkin",cliente_id:localStorage.getItem("userId")||"demo"};QRCode.toCanvas(document.getElementById("qr"),JSON.stringify(userData),{width:300,margin:2});</script></body></html>'},
    @{name="scanner.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Scanner - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head><body style="margin:0;font-family:Inter,sans-serif;background:#1a1a2e;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:24px 20px;text-align:center;"><h1 style="font-size:24px;font-weight:900;margin:0;"><i class="fas fa-qrcode"></i> Scanner QR Code</h1></header><div style="padding:32px 20px;text-align:center;"><div id="reader" style="max-width:500px;margin:0 auto;background:white;border-radius:16px;overflow:hidden;"></div></div></body></html>'},
    @{name="checkout-pontos.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Checkout - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:24px 20px;text-align:center;"><h1 style="font-size:24px;font-weight:900;margin:0;">Resgatar Pontos</h1></header><div style="max-width:600px;margin:0 auto;padding:32px 20px;"><div style="background:white;border-radius:24px;padding:32px;box-shadow:0 12px 40px rgba(102,126,234,0.08);text-align:center;"><p style="color:#7c8db0;margin:0;">Selecione o prêmio desejado para resgatar seus pontos.</p></div></div></body></html>'},
    @{name="categorias.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Categorias - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:24px 20px;text-align:center;"><h1 style="font-size:28px;font-weight:900;margin:0;">Categorias</h1></header><div style="max-width:1200px;margin:0 auto;padding:24px 20px;"><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px;"><div style="background:white;border-radius:16px;padding:24px;text-align:center;box-shadow:0 4px 12px rgba(102,126,234,0.08);"><h3 style="margin:0;color:#1a1a2e;">Restaurantes</h3></div></div></div></body></html>'},
    @{name="buscar.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Buscar - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:24px 20px;"><div style="max-width:800px;margin:0 auto;"><input type="text" placeholder="Buscar estabelecimentos..." style="width:100%;padding:16px 20px;border:none;border-radius:50px;font-size:16px;box-sizing:border-box;"></ style="width:100%;padding:16px 20px;border:none;border-radius:50px;font-size:16px;box-sizing:border-box;"></div></header><div style="max-width:1200px;margin:0 auto;padding:24px 20px;"><p style="color:#7c8db0;text-align:center;">Digite para buscar...</p></div></body></html>'},
    @{name="configuracoes.html"; content='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Configurações - Tem de Tudo</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></head><body style="margin:0;font-family:Inter,sans-serif;background:#f8f9ff;"><header style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:24px 20px;text-align:center;"><h1 style="font-size:28px;font-weight:900;margin:0;"><i class="fas fa-cog"></i> Configurações</h1></header><div style="max-width:800px;margin:0 auto;padding:24px 20px;"><div style="background:white;border-radius:20px;padding:24px;box-shadow:0 8px 24px rgba(102,126,234,0.08);"><h3 style="color:#1a1a2e;margin:0 0 16px;">Notificações</h3><label style="display:flex;align-items:center;gap:12px;cursor:pointer;"><input type="checkbox" checked><span style="color:#7c8db0;">Receber notificações</span></label></div></div></body></html>'}
)

foreach ($page in $pages) {
    $path = Join-Path $basePath $page.name
    $page.content | Out-File -FilePath $path -Encoding UTF8
    Write-Output "✅ $($page.name)"
}

Write-Output "`n🎉 TOTAL: $($pages.Count) páginas criadas!"
